export const games = [
    {
      id: "snake",
      name: "Snake",
      description: "El clásico juego de la serpiente. Come frutas y crece sin chocar contigo mismo o las paredes.",
      image: "https://i.pinimg.com/736x/38/fb/de/38fbdeaa36e0a6faec5e5c682d06fe78.jpg",
      year: "1976",
      category: "Arcade",
      frameType: "gameboy",
      color: "#4ade80",
    },
    {
      id: "tetris",
      name: "Tetris",
      description: "Organiza las piezas que caen para completar líneas y evitar que la pantalla se llene.",
      image: "https://i.pinimg.com/736x/e8/3f/aa/e83faa60a31d49d158f20fc5d5a9217b.jpg",
      year: "1984",
      category: "Puzzle",
      frameType: "gameboy",
      color: "#60a5fa",
    },
    {
      id: "pong",
      name: "Pong",
      description: "El primer videojuego exitoso. Controla una paleta y rebota la pelota contra tu oponente.",
      image: "https://i.pinimg.com/736x/64/9b/5e/649b5e5afd1d574343405139ad7b83b0.jpg",
      year: "1972",
      category: "Deportes",
      frameType: "tv",
      color: "#f97316",
    },
    {
      id: "breakout",
      name: "Breakout",
      description: "Destruye todos los bloques con una pelota rebotando, sin dejar que caiga.",
      image: "https://i.pinimg.com/736x/0a/4d/a8/0a4da8048f34dfd019c65fa8870e80b2.jpg",
      year: "1976",
      category: "Arcade",
      frameType: "tv",
      color: "#ec4899",
    },
    {
      id: "pacman",
      name: "Pac-Man",
      description: "Come todos los puntos del laberinto mientras evitas a los fantasmas.",
      image: "https://i.pinimg.com/736x/f9/3d/62/f93d62b808faf1e6b123b7f8fc8842b5.jpg",
      year: "1980",
      category: "Arcade",
      frameType: "tv",
      color: "#facc15",
    },
    {
      id: "space-invaders",
      name: "Space Invaders",
      description: "Defiende la Tierra de los invasores alienígenas disparándoles desde tu nave.",
      image: "https://i.pinimg.com/736x/6b/bc/d9/6bbcd95e1f751a22c7bfa6928823e4ee.jpg",
      year: "1978",
      category: "Shooter",
      frameType: "tv",
      color: "#10b981",
    },
  ]
  